name: Cancel Previous Runs

on:
  push:

jobs:
  cancel:
    name: Cancel
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        name: Cancel All
        with:
          workflow_id: 6161299
