name: Dotfiles Installation

on:
  push:
  schedule:
    - cron: '0 17 * * 4' # Every Thursday 5:00PM

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Clean up installed software
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          brew uninstall --cask --force $(brew list --cask)
          brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          rm -rf "$NVM_DIR"

      - name: Download and install available system updates
        run: |
          sudo softwareupdate -i -a

      - name: Clone this repository
        uses: actions/checkout@v2

      - name: Install using Makefile
        run: make

      - name: Run tests
        run: |
          brew install bats-core
          make test

#      - name: dotfiles
#        run: |
#          which dotfiles
#          dotfiles dock
#          dotfiles macos
#
#      - name: Verify runcom setup
#        run: source $HOME/.zshrc
